server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:~/poker
    username: admin
    password: admin
    platform: h2
  h2:
    console:
      path: /h2-console
      enabled: true
  jooq:
    sql-dialect: h2
