/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_.tables;


import com.whizzcode.data.database.public_.Indexes;
import com.whizzcode.data.database.public_.Keys;
import com.whizzcode.data.database.public_.Public;
import com.whizzcode.data.database.public_.tables.records.DecksRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Decks extends TableImpl<DecksRecord> {

    private static final long serialVersionUID = 812265045;

    /**
     * The reference instance of <code>PUBLIC.DECKS</code>
     */
    public static final Decks DECKS = new Decks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DecksRecord> getRecordType() {
        return DecksRecord.class;
    }

    /**
     * The column <code>PUBLIC.DECKS.DECK_ID</code>.
     */
    public final TableField<DecksRecord, Integer> DECK_ID = createField("DECK_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * Create a <code>PUBLIC.DECKS</code> table reference
     */
    public Decks() {
        this(DSL.name("DECKS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.DECKS</code> table reference
     */
    public Decks(String alias) {
        this(DSL.name(alias), DECKS);
    }

    /**
     * Create an aliased <code>PUBLIC.DECKS</code> table reference
     */
    public Decks(Name alias) {
        this(alias, DECKS);
    }

    private Decks(Name alias, Table<DecksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Decks(Name alias, Table<DecksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_3D);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DecksRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DECKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DecksRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3D;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DecksRecord>> getKeys() {
        return Arrays.<UniqueKey<DecksRecord>>asList(Keys.CONSTRAINT_3D);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Decks as(String alias) {
        return new Decks(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Decks as(Name alias) {
        return new Decks(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Decks rename(String name) {
        return new Decks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Decks rename(Name name) {
        return new Decks(name, null);
    }
}
