/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_.tables.records;


import com.whizzcode.data.database.public_.tables.Decks;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DecksRecord extends UpdatableRecordImpl<DecksRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 962969152;

    /**
     * Setter for <code>PUBLIC.DECKS.DECK_ID</code>.
     */
    public void setDeckId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DECKS.DECK_ID</code>.
     */
    public Integer getDeckId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Decks.DECKS.DECK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDeckId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDeckId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksRecord value1(Integer value) {
        setDeckId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DecksRecord
     */
    public DecksRecord() {
        super(Decks.DECKS);
    }

    /**
     * Create a detached, initialised DecksRecord
     */
    public DecksRecord(Integer deckId) {
        super(Decks.DECKS);

        set(0, deckId);
    }
}
