/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_.tables.records;


import com.whizzcode.data.database.public_.tables.DecksCards;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DecksCardsRecord extends TableRecordImpl<DecksCardsRecord> implements Record4<Integer, Integer, Integer, Boolean> {

    private static final long serialVersionUID = -2003472692;

    /**
     * Setter for <code>PUBLIC.DECKS_CARDS.DECK_ID</code>.
     */
    public void setDeckId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DECKS_CARDS.DECK_ID</code>.
     */
    public Integer getDeckId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DECKS_CARDS.CARD_ID</code>.
     */
    public void setCardId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.DECKS_CARDS.CARD_ID</code>.
     */
    public Integer getCardId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DECKS_CARDS.POSITION</code>.
     */
    public void setPosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.DECKS_CARDS.POSITION</code>.
     */
    public Integer getPosition() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DECKS_CARDS.DRAWN</code>.
     */
    public void setDrawn(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.DECKS_CARDS.DRAWN</code>.
     */
    public Boolean getDrawn() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DecksCards.DECKS_CARDS.DECK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DecksCards.DECKS_CARDS.CARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DecksCards.DECKS_CARDS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return DecksCards.DECKS_CARDS.DRAWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDeckId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getDrawn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDeckId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getDrawn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksCardsRecord value1(Integer value) {
        setDeckId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksCardsRecord value2(Integer value) {
        setCardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksCardsRecord value3(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksCardsRecord value4(Boolean value) {
        setDrawn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DecksCardsRecord values(Integer value1, Integer value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DecksCardsRecord
     */
    public DecksCardsRecord() {
        super(DecksCards.DECKS_CARDS);
    }

    /**
     * Create a detached, initialised DecksCardsRecord
     */
    public DecksCardsRecord(Integer deckId, Integer cardId, Integer position, Boolean drawn) {
        super(DecksCards.DECKS_CARDS);

        set(0, deckId);
        set(1, cardId);
        set(2, position);
        set(3, drawn);
    }
}
