/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_;


import com.whizzcode.data.database.public_.tables.Cards;
import com.whizzcode.data.database.public_.tables.Decks;
import com.whizzcode.data.database.public_.tables.DecksCards;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_3 = Indexes0.PRIMARY_KEY_3;
    public static final Index PRIMARY_KEY_3D = Indexes0.PRIMARY_KEY_3D;
    public static final Index CONSTRAINT_INDEX_6 = Indexes0.CONSTRAINT_INDEX_6;
    public static final Index CONSTRAINT_INDEX_6D = Indexes0.CONSTRAINT_INDEX_6D;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_3 = Internal.createIndex("PRIMARY_KEY_3", Cards.CARDS, new OrderField[] { Cards.CARDS.CARD_ID }, true);
        public static Index PRIMARY_KEY_3D = Internal.createIndex("PRIMARY_KEY_3D", Decks.DECKS, new OrderField[] { Decks.DECKS.DECK_ID }, true);
        public static Index CONSTRAINT_INDEX_6 = Internal.createIndex("CONSTRAINT_INDEX_6", DecksCards.DECKS_CARDS, new OrderField[] { DecksCards.DECKS_CARDS.DECK_ID }, false);
        public static Index CONSTRAINT_INDEX_6D = Internal.createIndex("CONSTRAINT_INDEX_6D", DecksCards.DECKS_CARDS, new OrderField[] { DecksCards.DECKS_CARDS.CARD_ID }, false);
    }
}
