/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_;


import com.whizzcode.data.database.public_.tables.Cards;
import com.whizzcode.data.database.public_.tables.Decks;
import com.whizzcode.data.database.public_.tables.DecksCards;
import com.whizzcode.data.database.public_.tables.records.CardsRecord;
import com.whizzcode.data.database.public_.tables.records.DecksCardsRecord;
import com.whizzcode.data.database.public_.tables.records.DecksRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CardsRecord, Integer> IDENTITY_CARDS = Identities0.IDENTITY_CARDS;
    public static final Identity<DecksRecord, Integer> IDENTITY_DECKS = Identities0.IDENTITY_DECKS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CardsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<DecksRecord> CONSTRAINT_3D = UniqueKeys0.CONSTRAINT_3D;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DecksCardsRecord, DecksRecord> CONSTRAINT_6 = ForeignKeys0.CONSTRAINT_6;
    public static final ForeignKey<DecksCardsRecord, CardsRecord> CONSTRAINT_6D = ForeignKeys0.CONSTRAINT_6D;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CardsRecord, Integer> IDENTITY_CARDS = Internal.createIdentity(Cards.CARDS, Cards.CARDS.CARD_ID);
        public static Identity<DecksRecord, Integer> IDENTITY_DECKS = Internal.createIdentity(Decks.DECKS, Decks.DECKS.DECK_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CardsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Cards.CARDS, "CONSTRAINT_3", Cards.CARDS.CARD_ID);
        public static final UniqueKey<DecksRecord> CONSTRAINT_3D = Internal.createUniqueKey(Decks.DECKS, "CONSTRAINT_3D", Decks.DECKS.DECK_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DecksCardsRecord, DecksRecord> CONSTRAINT_6 = Internal.createForeignKey(com.whizzcode.data.database.public_.Keys.CONSTRAINT_3D, DecksCards.DECKS_CARDS, "CONSTRAINT_6", DecksCards.DECKS_CARDS.DECK_ID);
        public static final ForeignKey<DecksCardsRecord, CardsRecord> CONSTRAINT_6D = Internal.createForeignKey(com.whizzcode.data.database.public_.Keys.CONSTRAINT_3, DecksCards.DECKS_CARDS, "CONSTRAINT_6D", DecksCards.DECKS_CARDS.CARD_ID);
    }
}
