/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_;


import com.whizzcode.data.database.DefaultCatalog;
import com.whizzcode.data.database.public_.tables.Cards;
import com.whizzcode.data.database.public_.tables.Decks;
import com.whizzcode.data.database.public_.tables.DecksCards;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -631557304;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CARDS</code>.
     */
    public final Cards CARDS = com.whizzcode.data.database.public_.tables.Cards.CARDS;

    /**
     * The table <code>PUBLIC.DECKS</code>.
     */
    public final Decks DECKS = com.whizzcode.data.database.public_.tables.Decks.DECKS;

    /**
     * The table <code>PUBLIC.DECKS_CARDS</code>.
     */
    public final DecksCards DECKS_CARDS = com.whizzcode.data.database.public_.tables.DecksCards.DECKS_CARDS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Cards.CARDS,
            Decks.DECKS,
            DecksCards.DECKS_CARDS);
    }
}
