/*
 * This file is generated by jOOQ.
*/
package com.whizzcode.data.database.public_;


import com.whizzcode.data.database.public_.tables.Cards;
import com.whizzcode.data.database.public_.tables.Decks;
import com.whizzcode.data.database.public_.tables.DecksCards;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CARDS</code>.
     */
    public static final Cards CARDS = com.whizzcode.data.database.public_.tables.Cards.CARDS;

    /**
     * The table <code>PUBLIC.DECKS</code>.
     */
    public static final Decks DECKS = com.whizzcode.data.database.public_.tables.Decks.DECKS;

    /**
     * The table <code>PUBLIC.DECKS_CARDS</code>.
     */
    public static final DecksCards DECKS_CARDS = com.whizzcode.data.database.public_.tables.DecksCards.DECKS_CARDS;
}
